# Java Home for Gradle (Java 21 required for Minecraft 1.21.4 / Loom)
# org.gradle.java.home=C:/Program Files/Java/jdk-21 - раскомментируй и поменяй под себя если надо
org.gradle.jvmargs=-Xmx3G

# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14

# Mod Properties
mod_version=1.0.2
maven_group=zov.viola
archives_base_name=viola